# Generated by Django 5.1 on 2024-08-30 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_usuarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
